billy/urls.py
from django.urls import path
from billy.views import *
app_name='mobile'
urlpatterns=[
    path('billy/',billy,name='billy'),
]

dilli/urls.py
from dilli.views import *
from django.urls import path
app_name='call'
urlpatterns=[
    path('dilli/',dilli,name='dilli'),
]

love_duo/urls.py
from django.contrib import admin
from django.urls import path,include
import dilli,billy

urlpatterns = [
    path("admin/", admin.site.urls),
    path("boy/",include('dilli.urls')),
    path("girl/",include('billy.urls')),
]

billy/models.py
from django.db import models

# Create your models here.

dilli/models.py
from django.db import models

# Create your models here.

billy/views.py
from django.shortcuts import render

# Create your views here.
def billy(request):
    return render(request,"billy.html")

dilli/views.py
from django.shortcuts import render

# Create your views here.
def dilli(request):
    return render(request,"dilli.html")

templates/billy.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>yes baby i am fine how are you</h1>
        <a href="{% url 'call:dilli' %}">go to dilli conversation</a>
    </center>
</body>
</html>

templates/dilli.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>dilli calls billy....</h1>
        <h1>billy picks up the phone...</h1>
        <a href="{% url 'mobile:billy' %}"><h1>hi baby how are you</h1></a>
    </center>
</body>
</html>